@extends('welcome')

@section('title','Privacy policy')
@section('content')
    <h1 class="c-headline">Privatumo politika</h1>
    <div><p><span style="color: #121212;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>Privatumo Politika</strong></span></span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>1. Kokią informaciją mes renkame?</strong></span></span></span></span><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">&nbsp;</span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Mes galime rinkti, saugoti ir naudoti žemiau nurodytų rūšių informaciją:</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">informaciją apie Jūsų kompiuterį ir apie Jūsų apsilankymus šioje interneto svetainėje bei naudojimąsi šia interneto svetaine (įskaitant Jūsų IP adresą, geografinę vietą, naršyklės tipą, iš kur buvote nukreiptas, lankymosi trukmę ir puslapių žiūrėjimų skaičių);</span></span></span></span></p>
        <p><span style="color: #000000;">&nbsp;•&nbsp;<span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">informaciją, kurią Jūs suteikiate mums tikslu prenumeruoti mūsų interneto svetainės paslaugas, pranešimus el.paštu ir/arba naujienlaiškius;</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">bet kokią kitą informaciją, kurią Jūs savo pasirinkimu siunčiate mums.</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>2. Slapukai</strong></span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Slapuką sudaro informacija, tinklo tarnybinės stoties siunčiama interneto naršyklei ir laikoma naršyklės. Ši informacija vėliau siunčiama atgal tarnybinei stočiai kaskart kai naršyklė paprašo puslapio iš tos tarnybinės stoties. Tai leidžia tai tinklo tarnybinei stočiai identifikuoti ir sekti interneto naršyklę. Mes naudojame Google Analytics naudojimuisi šia interneto svetaine analizuoti.</span></span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Google Analytics generuoja statistinę ir kitą informaciją apie naudojimąsi svetaine panaudodama slapukus, kurie laikomi vartotojų kompiuteriuose. Generuojama su mūsų interneto svetaine susijusi informacija yra naudojama kurti ataskaitas apie naudojimąsi šia interneto svetaine. Šią informaciją laikys Google. Google privatumo politika prieinama čia: http://www.google.com/privacypolicy.html . Pas mus besireklamuojantieji arba mokėjimo paslaugų teikėjai irgi gali siųsti Jums slapukus. Savo interneto svetainėje mes skelbiame Google Adsense interesais paremtas reklamas. Jas taip, kad atspindėtų Jūsų interesus, parenka Google. Kad nustatytų Jūsų interesus, Google seks Jūsų elgesį internete naudodama slapukus. Jūs galite peržiūrėti, ištrinti ir pridėti interesų kategorijas, susietas su Jūsų naršykle, naudodami Google bendrovės Ads Preference Manager, kurį galima rasti adresu http://www.google.com/ads/preferences/. Jūs galite atsisakyti Adsense partnerių tinklo slapuko adresu http://www.google.com/privacy_ads.html .</span></span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Tačiau šiame atsisakymo mechanizme naudojamas slapukas, ir jeigu Jūs ištrinsite slapukus iš savo kompiuterio, tai Jūsų atsisakymas nebus išsaugotas. Kad užsitikrintumėte, jog atsisakymas būtų išsaugotas konkrečiai naršyklei, turėtumėte naudoti Google naršyklės įskiepį, kurį galima rasti adresu http://www.google.com/ads/preferences/plugin . Dauguma naršyklių leidžia Jums nepriimti jokių slapukų, nors tam tikros naršyklės leidžia Jums nepriimti tik trečiųjų šalių slapukų. Pavyzdžiui, Internet Explorer naršyklėje galite atsisakyti visų slapukų spausdami „Tools“ &gt; „Internet Options“ &gt; „Privacy“ ir pasirinkdami „Block all cookies“ (tai daroma paslenkant perjungiklį). Tačiau visų slapukų blokavimas turės neigiamą įtaką galimybei naudotis daugeliu interneto svetainių, įskaitant šią.</span></span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>3. Jūsų asmeninių duomenų naudojimas</strong></span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Asmeniniai duomenys, pateikti šioje interneto svetainėje, bus naudojami tikslams, nurodytiems šioje privatumo politikoje arba aktualiose šios interneto svetainės dalyse. Mes galime naudoti jūsų asmeninę informaciją šiems tikslams:</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Interneto svetainei administruoti;</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Jūsų naršymo patirčiai gerinti, pritaikydami šią interneto svetainę asmeniniams poreikiams;</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">turint Jūsų sutikimą siųsti Jums el. paštu mūsų naujienlaiškį, kuris, mūsų manymu, gali būti Jums įdomus (Jūs galite bet kada informuoti mus, jeigu nebenorite, kad naujienlaiškis būtų Jums siunčiamas);</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;">&nbsp;• <span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">trečiosioms šalims suteikti statistinę informaciją apie mūsų vartotojus, tačiau ši informacija nebus naudojama jokiam atskiram vartotojui identifikuoti;</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Be aiškaus jūsų sutikimo mes neteiksime jūsų asmeninių duomenų jokioms trečiosioms šalims tiesioginės rinkodaros tikslais.</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>4. Politikos pakeitimai</strong></span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Mes galime retkarčiais atnaujinti šią privatumo politiką paskelbdami naują versiją savo interneto svetainėje. Kartkartėmis Jūs turėtumėte peržiūrėti šį puslapį, kad įsitikintumėte, jog esate patenkintas bet kokiais pasikeitimais.</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT"><strong>5. Trečiųjų šalių interneto svetainės</strong></span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Šioje interneto svetainėje yra nuorodų į kitas interneto svetaines. Mes nesame atsakingi už trečiųjų šalių interneto svetainių privatumo politikas ar praktikas.</span></span></span></span></p>
        <p>&nbsp;<span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Informacija apie internetinių ginčų sprendimus pagal str. 14 paragr. 1 ODR (Internetinių ginčų sprendimo reglamentas):</span></span></span></span></p>
        <p><span style="color: #000000;"><span style="font-family: Times New Roman, serif;"><span style="font-size: small;"><span lang="lt-LT">Europos Komisija duoda galimybę klientams išspręsti internetinius ginčus pagal str. 14 paragr. 1 ODR (Internetinių ginčų sprendimo reglamentas) ant vienos iš jų platformų. Platforma (http://ec.europa.eu/consumers/odr) pasitarnauja kaip vieta, kurioje vartotojai gali bandyti pasiekti sprendimus, kylančius iš pirkimo internetu ir paslaugų teikimo sutarties, be teismo įsikišimo.</span></span></span></span></p>
        <p>&nbsp;</p>
        <p>&nbsp;</p></div>
@endsection
