@extends('welcome')

@section('title','Regulations')
@section('content')
    {{ Breadcrumbs::render('regulations') }}
    <h1 class="c-headline">Nuostatai</h1>
    <div class="c-wysiwyg-content"><p><span style="color: #121212;"><span style="font-family: Times New Roman, serif;"><span lang="lt-LT"><strong>Sąlygos ir Taisyklės</strong></span></span></span></p>
        <p>&nbsp;</p>
        <p><a name="Bookmark"></a> <span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1. Bendrosios nuostatos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.1. Šios prekių pirkimo – pardavimo taisyklės (toliau – Taisyklės) yra Šalims privalomas teisinis dokumentas, kuris nustato Pirkėjo ir Pardavėjo teises, pareigas ir atsakomybę Pirkėjui įsigyjant prekes el. parduotuvėje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.2. Pardavėjas pasilieka teisę bet kuriuo metu pakeisti, taisyti ar papildyti taisykles, atsižvelgdamas į teisės aktų nustatytus reikalavimus. Pirkėjas informuojamas el. parduotuvės tinklalapyje. Pirkėjui apsiperkant el. parduotuvėje taikomos Taisyklės, galiojančios užsakymo pateikimo metu.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.3. Pirkti el. parduotuvėje turi teisę:</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.3.1. veiksnūs fiziniai asmenys, t.y. asmenys sulaukę pilnametystės, kurių veiksnumas nėra apribotas teismo tvarka;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.3.2. nepilnamečiai nuo 14 iki 18 metų amžiaus, tik turėdami tėvų arba rūpintojų sutikimą, išskyrus tuos atvejus, kai jie savarankiškai disponuoja savo pajamomis;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.3.3. juridiniai asmenys;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.3.4. visų aukščiau nurodytų asmenų įgaliotieji atstovai.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.4. Pardavėjas, patvirtindamas taisykles, taip pat garantuoja, kad, remiantis taisyklių 1.3. punktu, Pirkėjas turi teisę pirkti prekes el. parduotuvėje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.5. Sutartis tarp Pirkėjo ir Pardavėjo laikoma sudaryta nuo to momento, kai Pirkėjas el. parduotuvėje suformavęs prekių krepšelį, nurodęs pristatymo adresą, pasirinkęs atsiskaitymo būdą ir susipažinęs su Pardavėjo taisyklėmis, paspaudžia mygtuką „Patvirtinti užsakymą“ (žr. 5 punktą „Prekių užsakymas, kainos, atsiskaitymo tvarka, terminai“).</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">1.6. Kiekviena sutartis, sudaryta tarp Pirkėjo ir Pardavėjo, yra saugoma el. parduotuvėje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2. Asmens duomenų apsauga.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.1. Užsisakyti prekes el. parduotuvėje Pirkėjas gali:</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.1.1. užsiregistruodamas šioje el. parduotuvėje – įvesdamas registracijoje prašomus duomenis;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.1.2. nesiregistruodamas šioje el. parduotuvėje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.2. Pirkėjas, užsakydamas prekes 2.1. taisyklių punkte numatytais būdais, atitinkamuose Pardavėjo pateikiamuose informacijos laukuose turi nurodyti prekių užsakymo tinkamam įvykdymui būtinus Pirkėjo asmens duomenis: vardą, pavardę, prekių pristatymo adresą, telefono numerį ir el. pašto adresą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.3. Patvirtindamas šias taisykles Pirkėjas sutinka, jog 2.2. punkte pateikti Pirkėjo asmens duomenys būtų tvarkomi prekių ir paslaugų pardavimo el. parduotuvėje, Pardavėjo veiklos analizės ir tiesioginės rinkodaros tikslais.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.4. Sutikdamas, kad Pirkėjo asmens duomenys būtų tvarkomi prekių ir paslaugų pardavimo Pardavėjo el. parduotuvėje tikslu, Pirkėjas taip pat sutinka, kad Pirkėjo nurodytu el. pašto adresu ir telefono numeriu būtų siunčiami informaciniai pranešimai, būtini prekių užsakymui įvykdyti.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">2.5. Pirkėjas, užsiregistruodamas el. parduotuvėje bei užsakydamas prekes, įsipareigoja saugoti ir niekam neatskleisti prisijungimo duomenų.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3. Pirkėjo teisės ir įsipareigojimai.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.1. Pirkėjas turi teisę pirkti prekes el. parduotuvėje šių Taisyklių ir kitose šios el. parduotuvės informacijos skiltyse nustatyta tvarka.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.2. Pirkėjas turi teisę atsisakyti prekių pirkimo – pardavimo sutarties su el. parduotuve, pranešdamas Pardavėjui apie tai raštu (el. paštu, nurodant pageidaujamą grąžinti prekę ir jos užsakymo numerį) ne vėliau kaip per&nbsp;14 (keturiolika) darbo dienų nuo daikto pristatymo dienos, išskyrus atvejus, kai sutarties negalima atsisakyti pagal LR įstatymus (pvz., kai sutartis sudaryta dėl higienos prekių – patalynės reikmenų – pardavimo; žr. informaciją VšĮ „Vartotojų centras“ tinklalapyje http://www.vartotojucentras.lt/istatymas.php?id=1038, „Ne maisto prekių grąžinimo ir keitimo ypatumai“ 18 punktą.).</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.3. Taisyklių 3.2. punkte numatyta teise Pirkėjas gali pasinaudoti tik tuo atveju, jeigu prekė nebuvo sugadinta arba iš esmės nepasikeitė jos išvaizda, taip pat ji nebuvo naudojama.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.4. Pirkėjas įsipareigoja priimti užsakytas prekes ir už jas sumokėti sutartą kainą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.5. Jeigu pasikeičia Pirkėjo registracijos formoje pateikti duomenys, Pirkėjas privalo nedelsdamas juos atnaujinti.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.6. Pirkėjas įsipareigoja neperduoti tretiesiems asmenims savo prisijungimo duomenų. Jei Pirkėjas praranda prisijungimo duomenis, jis privalo nedelsiant informuoti apie tai Pardavėją skyriuje „Kontaktai“ nurodytomis susisiekimo priemonėmis.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">3.7. Pirkėjas, naudodamasis el. parduotuve, sutinka su šiomis pirkimo - pardavimo Taisyklėmis ir įsipareigoja jų laikytis bei nepažeisti LR teisės aktų.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">4. Pardavėjo teisės ir įsipareigojimai.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">4.1. Pardavėjas įsipareigoja sudaryti visas sąlygas Pirkėjui tinkamai naudotis el. parduotuvės teikiamomis paslaugomis.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">4.2. Jei Pirkėjas bando pakenkti Pardavėjo el. parduotuvės darbo stabilumui ir saugumui ar pažeidžia savo įsipareigojimus, Pardavėjas turi teisę nedelsiant ir be perspėjimo apriboti ar sustabdyti Pirkėjo galimybę naudotis el. parduotuve arba išskirtiniais atvejais panaikinti Pirkėjo registraciją.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">4.3. Pardavėjas įsipareigoja gerbti Pirkėjo privatumo teisę į Pirkėjo priklausančią asmeninę informaciją, nurodytą el. parduotuvės registracijos formoje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">4.4. Pardavėjas įsipareigoja pristatyti Pirkėjo užsakytas prekes Pirkėjo nurodytu adresu.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5. Prekių užsakymas, kainos, atsiskaitymo tvarka, terminai.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.1. El. parduotuvėje Pirkėjas gali pirkti visą parą, 7 dienas per savaitę.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.2. Sutartis pradeda galioti nuo to momento, kai Pirkėjas paspaudžia mygtuką „Patvirtinti užsakymą“, o gavęs užsakymą Pardavėjas jį patvirtina – atsiunčia patvirtinimo laišką Pirkėjo nurodytu el. paštu.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.3. Prekių kainos el. parduotuvėje ir suformuotame užsakyme nurodomos eurais, [</span></span><span style="font-family: Times New Roman, serif;"><span lang="lt-LT"><strong>įskaitant PVM</strong></span></span><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">].</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.4. Pirkėjas atsiskaito už prekes vienu iš šių būdų:</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.4.1. atsiskaitymas naudojantis el. bankininkyste – tai išankstinis apmokėjimas pasinaudojant Pirkėjo naudojama el. bankininkystės sistema. Pirkėjas, norėdamas pasinaudoti šia atsiskaitymo forma, turi būti pasirašęs el. bankininkystės sutartį su vienu iš žemiau nurodytų bankų: SEB bankas; AB „Swedbank“; „DNB“ bankas; „Danske“ bankas; „Nordea“ bankas. Pinigus Pirkėjas perveda į el. parduotuvės atsiskaitomąją sąskaitą. Atsakomybė už duomenų saugumą šiuo atveju tenka atitinkamam bankui, kadangi visos piniginės operacijos vyksta banko el. bankininkystės sistemoje.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.4.2. Atsiskaitymas banko pavedimu – tai išankstinis atsiskaitymas, kai Pirkėjas, atsispausdinęs užsakymą ir nuėjęs į artimiausią banko skyrių, perveda pinigus į el. parduotuvės banko sąskaitą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.5. Pirkėjas įsipareigoja už prekes sumokėti nedelsiant. Tik gavus apmokėjimą už prekes pradedamas formuoti prekių siuntinys ir pradedamas skaičiuoti prekių pristatymo terminas.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.6 Pardavėjas po užsakymo gavimo, patvirtina Pirkėjo užsakymo priėmimą ir nustato prekių patiekimo terminą. Tiekimo terminas nustatomas atskirai kiekvienam prekių užsakymui. Nesandeliuojamų prekių užsakymui įvykdymui užtikrinti, Pirkėjas, Pardavėjui pareikalavus, per 2 (dvi) darbo dienas, nuo užsakymo pateikimo dienos, sumoka Pardavėjui 50% dydžio užstatą nuo parduodamų nesandeliuojamų prekių bendros vertės, likusią vertės dalį, išankstiniu pavedimu arba grynaisiais pinigais, Pirkėjas sumoka atsiimdamas prekes. Jeigu Pirkėjas pavėluoja sumokėti užstatą daugiau, kaip 5 (penkias) kalendorines dienas, Pardavėjas turi teisę užsakymo vykdymą nutraukti.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">5.7 Pardavėjas po užsakymo gavimo, patvirtina Pirkėjo užsakymo priėmimą ir nustato prekių patiekimo terminą. Jeigu pirkėjas pasirinko už prekes sumokėti pristatymo metu ( C.O.D. Cash on delivery ) tuomet&nbsp;Pirkėjas prisiima atsakomybę už prekių apmokėjimą pristatymo metu. Jeigu pristatymo metu Pirkėjas atsisakys mokėti už užsakytas prekes arba atsisakys prekės kai ji jau išsiųsta Pirkėjo užsakymo metu nurodytu adresu tuomet Pardvėjas turi teisę iš Pirkėjo reikalauti padengti prekių siuntimo, pakavimo, pristatymo išlaidas arba 10% nuo užsakymo sumos. Pirkėjas pateikdamas užsakymą parduotuvėje patvirtina kad jam šios sąlygos yra aiškios ir jis&nbsp;su jomis sutinka.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6. Prekių pristatymas.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.1. Pirkėjas, užsakymo metu pasirinkęs prekių pristatymo paslaugą, įsipareigoja nurodyti tikslią prekių pristatymo vietą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.2. Pirkėjas įsipareigoja prekes priimti pats. Tuo atveju, jei Pirkėjas prekių pats priimti negali, o prekės pristatytos nurodytu adresu, Pirkėjas neturi teisės reikšti Pardavėjui pretenzijų dėl prekių pristatymo netinkamam subjektui.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.3. Prekes pristato Pardavėjas arba Pardavėjo įgaliotas atstovas (kurjeris).</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.4. Pardavėjas pristato Pirkėjui prekes vadovaudamasis prekių aprašymuose nurodytais terminais. Šie terminai yra preliminarūs, be to, netaikomi tais atvejais, kai Pardavėjo sandėlyje nėra reikiamų prekių, o Pirkėjas informuojamas apie užsakytų prekių trūkumą. Kartu Pirkėjas sutinka, jog išimtiniais atvejais prekių pateikimas gali vėluoti dėl nenumatytų, nuo Pardavėjo nepriklausančių aplinkybių. Tokiu atveju Pardavėjas įsipareigoja nedelsiant susisiekti su Pirkėju ir suderinti prekių pateikimo sąlygas.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.5. Visais atvejais Pardavėjas atleidžiamas nuo atsakomybės už prekių pateikimo terminų pažeidimą, jeigu prekės Pirkėjui nėra pateikiamos arba pateikiamos ne laiku dėl Pirkėjo kaltės arba dėl nuo Pardavėjo nepriklausančių aplinkybių.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.6. Pirkėjas privalo visais atvejais nedelsiant informuoti Pardavėją, jeigu siunta pateikiama sulamdytoje arba kitu būdu pažeistoje pakuotėje, jeigu siuntoje pateikiamos neužsakytos prekės arba netinkamas jų kiekis, nepilna prekės komplektacija. Pretenzijos dėl netinkamo prekės kiekio priimamos 12 valandų bėgyje nuo prekės pristatymo laiko. Vėliau pretenzijos nepriimamos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.7. Pirkėjas visais atvejais pristatymo metu pastebėjęs pakuotės pažeidimus privalo kurjerio pateikiamame siuntos pristatymo dokumente nurodyti pastabas arba surašyti atskirą aktą dėl šių pažeidimų. Tai Pirkėjas privalo padaryti dalyvaujant kurjeriui. Neatlikus tokių veiksmų Pardavėjas yra atleidžiamas nuo atsakomybės prieš Pirkėją dėl prekių pažeidimų, susijusių su pakuotės pažeidimais, kurių Pirkėjas nepažymėjo kurjerio prekės pristatymo dokumente.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">6.8 Prekių pristatymas (transportavimas) kainuoja nuo [</span></span><span style="font-family: Times New Roman, serif;"><span lang="lt-LT"><strong>6 eur</strong></span></span><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">] VISOJE LIETUVOJE*. Tiksli prekių pristatymo kaina apskaičiuojama užsakymo pateikimo metu, nes priklauso nuo užsakymo vertės.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">*prekių pristatymo kaina gali keistis priklausomai nuo vietovės ir turi būti derinama kiekvienam užsakymui individualiai.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">*pristatymas į Kuršių Neriją papildomai kainuoja 40 eur.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">*pardavėjas neteikia užnešimo paslaugos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">7. Prekių kokybės, garantijos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">7.1. Kiekvienos el. parduotuvėje parduodamos prekės duomenys bendrai nurodomi prie kiekvienos prekės esančiame prekės aprašyme.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">7.2. Pardavėjas neatsako už tai, kad el. parduotuvėje esančios prekės savo spalva, forma ar kitais parametrais gali neatitikti realaus prekių dydžio, formų ir spalvos dėl Pirkėjo naudojamo vaizduoklio ypatybių.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">7.3. Pardavėjas tam tikroms prekių rūšims suteikia tam tikrą laiką galiojančią kokybės garantiją, kurios konkretus terminas ir kitos sąlygos nurodomos tokių prekių aprašymuose.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">7.4. Pardavėjui tam tikroms prekių rūšims nesuteikus kokybės garantijos, galioja garantija, numatyta atitinkamų teisės aktų arba taikoma Gamintojo garantija.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8. Prekių grąžinimas ir keitimas.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.1. Parduotų prekių trūkumai šalinami, nekokybiškos prekės keičiamos, grąžinamos vadovaujantis LR ūkio ministro 2001 m. birželio 29 d. įsakymu Nr. 217 „Dėl Daiktų grąžinimo ir keitimo taisyklių patvirtinimo“ patvirtintomis Daiktų grąžinimo ir keitimo taisyklėmis, išskyrus atvejus, kai sutarties negalima atsisakyti pagal LR įstatymus (kai sutartis sudaryta dėl higienos prekių – patalynės reikmenų – pardavimo; žr. informaciją VšĮ „Vartotojų centras“ tinklalapyje http://www.vartotojucentras.lt/istatymas.php?id=1038, „Ne maisto prekių grąžinimo ir keitimo ypatumai“ 18 punktą.). Pinigai už grąžintas prekes visais atvejais pervedami tik į mokėtojo banko sąskaitą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.2. Norėdamas grąžinti prekę(-es) remiantis Taisyklių 8.1. punktu, Pirkėjas gali tai padaryti per 7 (septynias) darbo dienas nuo prekių pristatymo Pirkėjui dienos, informuodamas Pardavėją kontaktų skyriuje nurodytomis susisiekimo priemonėmis, nurodant grąžinamos prekės pavadinimą, užsakymo numerį ir grąžinimo priežastis.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3. Pirkėjui grąžinant prekes, būtina laikytis šių sąlygų:</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3.1. grąžinama prekė turi būti originalioje tvarkingoje pakuotėje;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3.2. prekė turi būti Pirkėjo nesugadinta;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3.3. prekė turi būti nenaudota, nepraradusi prekinės išvaizdos (nepažeistos etiketės, nenuplėštos apsauginės plėvelės ir kt.) (šis punktas netaikomas tuo atveju, kai grąžinama nekokybiška prekė);</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3.4. grąžinama prekė turi būti tos pačios komplektacijos, kokios Pirkėjas ją gavo;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.3.5. grąžinant prekę būtina pateikti jos įsigijimo dokumentą.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.4. Pardavėjas turi teisę nepriimti Pirkėjo grąžinamų prekių, jei Pirkėjas nesilaiko 8.3. straipsnyje nustatytos prekių grąžinimo tvarkos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.5. Grąžinant gautą ne tą prekę ir/ar nekokybišką prekė, Pardavėjas įsipareigoja atsiimti tokias prekes ir jas pakeisti analogiškomis tinkamomis prekėmis.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">8.6. Tuo atveju, kai Pardavėjas neturi pakeitimui tinkamų prekių, Pirkėjui grąžinama sumokėta suma,&nbsp;atminusavus pristatymo ir pakavimo išlaidas**.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">**Pristatymo išlaidos&nbsp;skaičiuojamo pagal kurjerio galiojantį kainoraštį.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">**Pakavimo išlaidos siekia 3,00 eur vienai prekei.&nbsp;</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9. Pirkėjo ir pardavėjo atsakomybė.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.1. Pirkėjas yra visiškai atsakingas už Pirkėjo pateikiamų asmens duomenų teisingumą. Jei Pirkėjas nepateikia tikslių asmens duomenų registracijos formoje, Pardavėjas neatsako už dėl to atsiradusius padarinius ir įgyja teisę reikalauti iš Pirkėjo patirtų tiesioginių nuostolių atlyginimo.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.2. Pirkėjas atsako už veiksmus, atliktus naudojantis šia el. parduotuve.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.3. Užsiregistravęs Pirkėjas atsako už savo prisijungimo duomenų perdavimą tretiesiems asmenims. Jei el. parduotuvės teikiamomis paslaugomis naudojasi trečiasis asmuo, prisijungęs prie el. parduotuvės naudodamasis Pirkėjo prisijungimo duomenimis, Pardavėjas šį asmenį laikome Pirkėju.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.4. Pardavėjas atleidžiamas nuo bet kokios atsakomybės tais atvejais, kai nuostoliai kyla dėl to, jog Pirkėjas, neatsižvelgdamas į Pardavėjo rekomendacijas ir Pirkėjo įsipareigojimus, nesusipažino su šiomis Taisyklėmis, nors tokia galimybė jam buvo suteikta.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.5. Jei Pardavėjo el. parduotuvėje yra nuorodos į kitų įmonių, įstaigų, organizacijų ar asmenų el. tinklalapius, Pardavėjas nėra atsakingas už ten esančią informaciją ar vykdomą veiklą, tų tinklapių neprižiūri, nekontroliuoja ir toms įmonėms bei asmenims neatstovauja.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">9.6. Atsiradus žalai, kaltoji Šalis atlygina kitai Šaliai tiesioginius nuostolius.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10. Rinkodara ir informacija.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10.1. Pardavėjas savo nuožiūra gali inicijuoti el. parduotuvėje įvairias akcijas.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10.2. Pardavėjas turi teisę vienašališkai, be atskiro įspėjimo, pakeisti akcijų sąlygas, taip pat jas panaikinti. Bet koks akcijų sąlygų ir tvarkos pakeitimas ar panaikinimas galioja tik į priekį, t.y. nuo jų atlikimo momento.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10.3. Pardavėjas visus pranešimus siunčia Pirkėjo registracijos formoje nurodytomis susisiekimo priemonėmis.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10.4. Pirkėjas visus pranešimus ir klausimus siunčia Pardavėjo el. parduotuvės skyriuje „Kontaktai“ nurodytais telefonais ir el. pašto adresais.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">10.5. Pardavėjas neatsako jei Pirkėjas negauna siunčiamų informacinių ar patvirtinančių pranešimų dėl internetinio ryšio, elektroninio pašto paslaugų tiekėjų tinklų sutrikimų.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">11. Baigiamosios nuostatos.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">11.1. Šios prekių pirkimo – pardavimo Taisyklės sudarytos vadovaujantis LR įstatymais ir teisės aktais.</span></span></p>
        <p><span style="font-family: Times New Roman, serif;"><span lang="lt-LT">11.2. Visi nesutarimai, kilę dėl šių Taisyklių vykdymo, sprendžiami derybų būdu. Nepavykus susitarti, ginčai sprendžiami LR įstatymų nustatyta tvarka.</span></span></p>
        <p>&nbsp;</p></div>
@endsection
